#!/bin/bash

echo "🔍 GitHub Repository Configuration Checklist"
echo "============================================"

echo ""
echo "📋 Step 1: Verify GitHub Repository Secrets"
echo "-------------------------------------------"
echo "Go to your GitHub repository and check:"
echo "1. Repository → Settings → Secrets and variables → Actions"
echo "2. Look for these secrets:"
echo "   ✅ AWS_ROLE_ARN=arn:aws:iam::874834750693:role/product-mindset-github-actions-dev"
echo "   ✅ AWS_REGION=us-east-1"
echo "   ✅ NIM_API_KEY=your_nvidia_api_key"
echo "   ✅ POSTGRES_PASSWORD=your_secure_password"
echo ""
echo "If AWS_ROLE_ARN is missing, add it with the value above."

echo ""
echo "📋 Step 2: Verify GitHub Repository Permissions"
echo "----------------------------------------------"
echo "Go to your GitHub repository and check:"
echo "1. Repository → Settings → Actions → General"
echo "2. Under 'Workflow permissions':"
echo "   ✅ Select 'Read and write permissions'"
echo "   ✅ Check 'Allow GitHub Actions to create and approve pull requests'"
echo ""
echo "3. Under 'Fork pull request workflows from outside collaborators':"
echo "   ✅ Select 'Require approval for first-time contributors' (recommended)"

echo ""
echo "📋 Step 3: Verify Repository Name"
echo "--------------------------------"
echo "Current trust policy expects repository: stevei101/hack-a-product"
echo "Your actual repository should be: $(git remote get-url origin 2>/dev/null | sed 's/.*github.com[:/]\([^.]*\).*/\1/' || echo 'Cannot determine from git remote')"
echo ""
echo "If the repository names don't match, we need to update the trust policy."

echo ""
echo "📋 Step 4: Check GitHub Actions Settings"
echo "---------------------------------------"
echo "Go to your GitHub repository and check:"
echo "1. Repository → Settings → Actions → General"
echo "2. Make sure 'Allow all actions and reusable workflows' is selected"
echo "3. Or at minimum 'Allow local actions and reusable workflows'"

echo ""
echo "📋 Step 5: Verify Branch Protection (if any)"
echo "-------------------------------------------"
echo "If you have branch protection rules:"
echo "1. Go to Repository → Settings → Branches"
echo "2. Make sure 'Allow specified actors to bypass required pull requests' includes:"
echo "   - GitHub Actions"
echo "   - Your GitHub username"

echo ""
echo "🔧 Quick Fix Commands"
echo "====================="
echo ""
echo "If you need to update the trust policy for a different repository:"
echo ""
echo "1. Get your repository name:"
echo "   REPO_NAME=\$(git remote get-url origin | sed 's/.*github.com[:/]\\([^.]*\\).*/\\1/')"
echo "   echo \"Repository: \$REPO_NAME\""
echo ""
echo "2. Update the trust policy (replace with your actual repository):"
echo "   aws iam update-assume-role-policy --role-name product-mindset-github-actions-dev --policy-document '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Federated\":\"arn:aws:iam::874834750693:oidc-provider/token.actions.githubusercontent.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\",\"Condition\":{\"StringEquals\":{\"token.actions.githubusercontent.com:aud\":\"sts.amazonaws.com\"},\"StringLike\":{\"token.actions.githubusercontent.com:sub\":\"repo:YOUR_ORG/YOUR_REPO:ref:refs/heads/*\"}}}]}'"

echo ""
echo "🚨 Common Issues & Solutions"
echo "============================"
echo ""
echo "❌ 'Credentials could not be loaded'"
echo "   → Check AWS_ROLE_ARN secret exists in GitHub"
echo "   → Verify repository permissions allow Actions"
echo "   → Ensure trust policy matches your repository name"
echo ""
echo "❌ 'Access denied'"
echo "   → Check IAM role has necessary permissions"
echo "   → Verify OIDC provider is configured correctly"
echo ""
echo "❌ 'Role not found'"
echo "   → Verify the role ARN is correct"
echo "   → Check the role exists in the correct AWS account"

echo ""
echo "📞 Next Steps"
echo "============="
echo "1. Verify all the checklist items above"
echo "2. Push a change to trigger the workflow"
echo "3. Check the Actions tab for detailed error logs"
echo "4. If still failing, check CloudTrail logs in AWS for AssumeRoleWithWebIdentity failures"
